### ISSUE TITLE
The getter 'BASE64' isn't defined for the class 'tripledes::BlockCipher'.

### ISSUE THREAD

**Issue by NTMS2017** [johnpryan/tripledes-dart#5]
I try this and got same error
capital@capital-virtual-machine:/aqueduct3_pro/capitalapi$ aqueduct --version
Aqueduct CLI version: 3.0.0-beta.1
capital@capital-virtual-machine:/aqueduct3_pro/capitalapi$ dart --version
Dart VM version: 2.0.0-dev.69.4 (Unknown timestamp) on "linux_x64"
capital@capital-virtual-machine:~/aqueduct3_pro/capitalapi$ aqueduct serve
-- Aqueduct CLI Version: 3.0.0-beta.1
-- Aqueduct project version: 3.0.0-beta.1
-- Preparing...
*** Uncaught error
**IsolateSpawnException: Unable to spawn isolate: file:///home/capital/.pub-cache/hosted/pub.dartlang.org/tripledes-2.0.1/lib/tripledes.dart:32:12: Error: Getter not found: 'BASE64'.
return BASE64.encode(encode(message).codeUnits);**
^^^^^^
file:///home/capital/.pub-cache/hosted/pub.dartlang.org/tripledes-2.0.1/lib/tripledes.dart:32:12: Error: The getter 'BASE64' isn't defined for the class 'tripledes::BlockCipher'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'BASE64'.
return BASE64.encode(encode(message).codeUnits);

**Comment by johnpryan** [comment]
Good catch!

This package is not Dart 2 compatible yet. In Dart 2, BASE64 changed to base64 I think.

**Comment by NTMS2017** [comment]
thanks for update, I create a new dart console app (always test my dart code before move to Flutter) but I am getting new error as follows;

**my pubspec.yaml file**

```
name: untitled2
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: niyazitoros <email@example.com>

environment:
  sdk: '>=2.0.0-dev.68.0 <3.0.0'

dependencies:
  tripledes: "^2.1.0"

dev_dependencies:
  test: ^1.0.0
```

**And the error is:**

```
Working dir: /Users/niyazitoros/IdeaProjects/untitled2
/usr/local/opt/dart/libexec/bin/pub get
Resolving dependencies...
The current Dart SDK version is 2.0.0-dev.69.5.

Because untitled2 depends on tripledes >=2.1.0 which requires SDK version >=2.0.0 <3.0.0, version solving failed.
Process finished with exit code 1
```
